#! /usr/bin/env bash

lockscreen() {
    swaylock \
	--screenshots \
	--indicator-radius 100 \
	--indicator-thickness 7 \
	--effect-blur 7x5 \
	--effect-vignette 0.5:0.5 \
	--ring-color 4f53c8 \
	--key-hl-color 880033 \
	--line-color 00000000 \
	--inside-color 00000088 \
	--separator-color 00000000 \
	--grace 1 \
	--fade-in 0.2
}

# Times the screen off and puts it to background

lockscreen_with_idle() {
	swayidle \
		timeout 300 'hyprctl dispatch dpms off' \
		resume 'hyprctl dispatch dpms on'  &
	lockscreen
	
	# Kills last background task so idle timer doesn't keep running
	kill %%
}

case "$1" in
	--idle)
		lockscreen_with_idle
		;;
	--help)
		echo "Usage: $0 {--idle}"
		echo "--idle: Locks the screen after 5 minutes and turns off the display."
		;;
	*)
		lockscreen
		;;
esac

