#! /usr/bin/env bash

WALLPAPERS_DIR="$HOME/wallpapers"
RECENT_WALLPAPERS_FILE="$HOME/.cache/recent_wallpapers"


random_wallpaper() {
    recent_wallpapers=$(tail -n 3 "${RECENT_WALLPAPERS_FILE}")
    if [ -z "$recent_wallpapers" ]; then
        find_command="find ${WALLPAPERS_DIR} -type f"
    else
        find_command="find ${WALLPAPERS_DIR} -type f $(printf "! -wholename %s " $recent_wallpapers)"
	fi
    wallpaper_file=$(eval "${find_command}" | shuf -n1)
    echo "$(tail -n 2 "${RECENT_WALLPAPERS_FILE}")" > "${RECENT_WALLPAPERS_FILE}"
    echo "${wallpaper_file}" >> "${RECENT_WALLPAPERS_FILE}"
    swww img "${wallpaper_file}" --transition-step 10 --transition-fps 120 --transition-type center --transition-duration 2  
}

set_wallpaper() {
    last_wallpaper=$(realpath $1)
    swww img "${last_wallpaper}" --transition-step 10 --transition-fps 120 --transition-type center --transition-duration 2
    echo "${last_wallpaper}" >> "${RECENT_WALLPAPERS_FILE}"
}

case "$1" in
    --random)
        random_wallpaper
        ;;
    --set)
        set_wallpaper "$2"
        ;;
    *)
        echo "Usage: $0 {random|set <file_path>}"
        exit 1
esac

